### ISSUE TITLE
Can't see node-red-contrib-graphs in node page

### ISSUE THREAD

**Issue by cba16** [IBM-IoT/node-red-contrib-graphs#9]
Hi,

I imported node-red-contrib-graphs and added it to the json file in DevOps so it seems to be installed but when in open my application in node red I can't see any new node. What did I miss? Is there a bug?
Thanks!

**Comment by chiefkarlin** [comment]
@cba16 ...

I ran into this issue as well when using this module from Bluemix - I believe it is due to the way that the Bluemix settings setup the environment for running node-red.  If you tail the output of your application using the 'cf tail <appname>' command, you would see an error output by node-red-contrib-graphs indicating a TypeError:
`
2016-06-09T12:26:41.59-0500 [App/0]      OUT 9 Jun 17:26:41 - [warn] ------------------------------------------
2016-06-09T12:26:41.59-0500 [App/0]      OUT 9 Jun 17:26:41 - [warn] [datasource] TypeError: Arguments to path.join must be strings
2016-06-09T12:26:41.59-0500 [App/0]      OUT 9 Jun 17:26:41 - [warn] ------------------------------------------
`
From looking at the code, this appears to be caused by the users.js file attempting to setup some local storage to serialize the dashboard based on the value of RED.settings.userDir.  It appears that this value does not exist in the default bluemix-settings.js file that is passed to node-red, resulting in the error above when trying to create the storage path.

A simple work-around is to edit your bluemix-settings.js and add a line to assign the userDir directory to your app directory in the settings object:

`
From bluemix-settings.js



var settings = module.exports = {
    uiPort: process.env.VCAP_APP_PORT || 1880,
    mqttReconnectTime: 15000,
    serialReconnectTime: 15000,
    debugMaxLength: 1000,

    // Add the bluemix-specific nodes in
    nodesDir: path.join(__dirname,"nodes"),
    
    //RJV - added for node-red-contrib-graphs workaround
    userDir: __dirname,

    // Blacklist the non-bluemix friendly nodes
    nodesExcludes:['66-mongodb.js','75-exec.js','35-arduino.js','36-rpi-gpio.js','25-serial.js','28-tail.js','50-file.js','31-tcpin.js','32-udp.js','23-watch.js'],

    // Enable module reinstalls on start-up; this ensures modules installed
    // post-deploy are restored after a restage
    autoInstallModules: true,

    // Move the admin UI
    httpAdminRoot: '/red',

    // You can protect the user interface with a userid and password by using the following property
    // the password must be an md5 hash  eg.. 5f4dcc3b5aa765d61d8327deb882cf99 ('password')
    //httpAdminAuth: {user:"user",pass:"5f4dcc3b5aa765d61d8327deb882cf99"},

    // Serve up the welcome page
    httpStatic: path.join(__dirname,"public"),

    functionGlobalContext: { },

    storageModule: require("./couchstorage")
}

`
Hope this helps!
Rob

**Comment by cba16** [comment]
Great, it works, thanks a lot! (excuse my late reply)

**Comment by cristian-t** [comment]
Created issue #12 to keep track of this defect.
